### ISSUE TITLE
typo sur watchghost dans les sprints

### ISSUE THREAD

**Issue by arthurlogilab** [AFPy/pyconfr_2019#17]
s/focntionnement/fonctionnement/ dans https://www.pycon.fr/2019/fr/talks/sprint.html

J'aurais fait une MR mais je ne trouve pas d'où viennent les données.

**Comment by liZe** [comment]
C'est corrigé, merci ! Les infos viennent du logiciel qui gère les conférences.

**Comment by arthurlogilab** [comment]
merci!
