### ISSUE TITLE
Erreur sur les jours du sprint django-elasticsearch-dsl

### ISSUE THREAD

**Issue by alexgarel** [AFPy/pyconfr_2019#18]
sur https://www.pycon.fr/2019/fr/talks/sprint.html 

> Contributions à django-elasticsearch-dsl,,Par Alexandre Garel − Jeudi et vendredi de 10 h 00 à 18 h 00 

Or j'avais précisé que je ne serais là que le vendredi ! C'est possible de corriger ?

**Comment by liZe** [comment]
C'est corrigé !

**Comment by alexgarel** [comment]
Merci :-)
