### ISSUE TITLE
Affiches

### ISSUE THREAD

**Issue by liZe** [AFPy/pyconfr_2019#5]
Comme d'hab en A3.

**Comment by Seluj78** [comment]
@liZe une autre issue pour des stickers ? des tshirts ? (pour y penser ?)

**Comment by liZe** [comment]
Pour les stickers et le tshirt, je pense qu'on peut se limiter au logo, non ?

**Comment by Seluj78** [comment]
Oui bien sur, mais c'est pour y penser ;)
Je metterais bien un sticker bonus: https://twitter.com/lisroach/status/1136415288784609281?s=09

**Comment by liZe** [comment]
Héhé, OK. J'avais mis juste les tickets pour le graphisme et le code, pas toute l'orga. Je pense qu'on écrira tout dans le détail après notre petite réunion du bureau :smile:.

**Comment by liZe** [comment]
@annabellou C'est tout bon pour l'affiche, on a tous les logos des sponsors (tous en SVG) sur https://www.pycon.fr/2019/fr/sponsors.html. Tu peux bien évidemment cloner ce dépôt pour les récupérer tous d'un coup. Il manque juste Google qui est sponsor Platine et qui n'a pas (encore) donné son logo.

**Comment by Seluj78** [comment]
@liZe Est ce que on a un logo final pour l'event ? pour Stickermule

**Comment by liZe** [comment]
> @liZe Est ce que on a un logo final pour l'event ? pour Stickermule

Pour tout ce qui est logos, tu peux voir avec Lucien.

**Comment by annabellou** [comment]
Affiche A3 CMJN
[Pycon 2019 Affiche.pdf](https://github.com/AFPy/pyconfr_2019/files/3717639/Pycon.2019.Affiche.pdf)

Affiche A3 CMJN avec des fonds perdus de 5mm
[Pycon 2019 Affiche - fonds perdus.pdf](https://github.com/AFPy/pyconfr_2019/files/3717643/Pycon.2019.Affiche.-.fonds.perdus.pdf)

**Comment by liZe** [comment]
Quelques petits changements en cours :
- Mettre « Campus de Talence » plutôt que « Université de Talence ».
- Enlever les sponsors Cœur.

**Comment by Seluj78** [comment]
On rajoute que c'est gratuit ?

**Comment by liZe** [comment]
> On rajoute que c'est gratuit ?

On l'a pas mis les autres années, on le mettra l'année prochaine :p.

**Comment by annabellou** [comment]
Du coup, les versions corrigées : 

- Affiche A3 CMJN 
[Pycon 2019 Affiche.pdf](https://github.com/AFPy/pyconfr_2019/files/3717752/Pycon.2019.Affiche.pdf)

- Affiche A3 CMJN avec des fonds perdus de 5mm
[Pycon 2019 Affiche - fonds perdus.pdf](https://github.com/AFPy/pyconfr_2019/files/3717753/Pycon.2019.Affiche.-.fonds.perdus.pdf)
