### ISSUE TITLE
Encart pour GNU/Linux Magazine

### ISSUE THREAD

**Issue by liZe** [AFPy/pyconfr_2019#6]
> Format utile :
> 105 mm (l) x 140 mm (h)
> Format avec bords perdus :
> 155 mm (h) x 120 mm (h)
> Fichier en Pdf, CMJN, 300 Dpi
>
> Visuel à nous remettre le vendredi 2 Août.

**Comment by annabellou** [comment]
Visuel envoyé et bien réceptionné par Valérie aujourd'hui !

**Comment by liZe** [comment]
:heart:
