### ISSUE TITLE
Encart pour StickerMule

### ISSUE THREAD

**Issue by Seluj78** [AFPy/pyconfr_2019#8]
Ils nous envoient 800 stickers avec le logo de la PyCon de cette année dès que leur logo et leur lien est sur notre site. CF mail recu sur la trésorerie. cc @liZe 

> Please find attache our logo, it should be put on the event website and linked to the following adderess: http://stickermule.com/supports/pyconfr19-sponsorship

> Please let me know when our logo is online. I'm looking forward to receving your artworks for the stickers!

**Comment by liZe** [comment]
C'est en ligne, tu peux les prévenir :smile:.

**Comment by Seluj78** [comment]
Hello, ca me semble pas ok de mon coté :/ pas d'image + pas de lien
<img width="864" alt="Screenshot 2019-06-30 at 21 12 19" src="https://user-images.githubusercontent.com/4641317/60401002-cf237180-9b7b-11e9-8941-7fd0da308c70.png">

**Comment by Seluj78** [comment]
Alors sur mobile c'est ok mais pas sur mon ordi :/ et le lien ne semble pas etre le bon

**Comment by Seluj78** [comment]
#9

**Comment by Seluj78** [comment]
hmm, le CSS est ok ?

<img width="1144" alt="Screenshot 2019-06-30 at 21 32 56" src="https://user-images.githubusercontent.com/4641317/60401240-a81a6f00-9b7e-11e9-9e6e-6067d83dafdc.png">

**Comment by liZe** [comment]
Je fais en sorte que le contenu s'affiche correctement, c'est Lucien qui doit bosser pour que le style soit amélioré. Pour l'instant c'est largement suffisant.
